# Replace the text below to customize your site
site_name: June Bascaran - MDEF Blog
site_description: Master in Design for Emergent Futures
site_author: June
copyright: Copyleft 2021 "June" - GNU Free Documentation License
repo_name: 'JuneBascaran/MDEF'
site_url: https://junebascaran.github.io/MDEF/
repo_url: 'https://github.com/JuneBascaran/MDEF'


nav:
  - Home: index.md
  - About me: about/me.md
  - master_proyect:
      - Term 1: 
          - Hacking Food Supply Chain: project/Hacking Food Supply Chain.md

  - Design Studio:
      - RtD Toolbox: designstudio/01-RtD-Toolbox.md
      - Communication Strategy: designstudio/02-Communication Strategy.md
      - Repositioning: designstudio/03-Repositioning.md
      - Radical Situadness: designstudio/04-Radical Situadness.md

  - Reflections :
      - Term 1:
          - Bootcamp: term1/01-Bootcamp.md
          - AoWS: term1/02-Atlas of Weak Signals.md
          - Bio & AgriZero: term1/03-Bio&AgriZero.md
          - Living With Our Own Ideas: term1/04-Living With Our Own Ideas.md
          - Tech Beyond the Mith: term1/05-Tech Beyond the Mith.md
          - Community Engagement: term1/06-Community Engagement
          - Extended Intelligences: term1/07-Extended Intelligence
          
      - Term 2:
          - Design for the Next Billion Seconds: term2/01-Design for the next second billion.md
          - Remixing Materials: term2/02-Remixing Materials.md
          - Prototyping for design: term2/03-Prototyping for design.md
          - Making sense & meaning: term2/04-Making sense & meaning.md
          - Communicating ideas: term2/05-Communicating Ideas.md

      
        
        



extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/medium
      link: https://medium.com/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/"
    - icon: fontawesome/brands/github
      link: "https://github.com/"

theme:
  name: material
  logo: images/logo/IMG-0930.jpg
  favicon: images/logo/IMG-0930.jpg
  

  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: white
    accent: deep orange
  font:
    # See available fonts at https://fonts.google.com/
    text: Lato
    code: Lato

  features:
    # - navigation.tabs
    # - navigation.tabs.sticky
    - instant
    # - navigation.expand
    # - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    # - navigation.top
    # - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
